### ISSUE TITLE
[建议]  打开本地已有的项目时,依旧按照规定目录分层。

### ISSUE THREAD

**Issue by FantasyGao** [axetroy/vscode-gpm#1]
当我打开已有的git项目时（没有通过gpm clone下来的），依旧按照第一级‘域名类’，第二级‘用户类’，第三级‘项目类’，前两级不可以‘‘open in window’’，但实际上此时的项目没有一二级分类。
（自己建两层目录可以充当一二级分类，但是工作的时候，一般一层或者两层目录，不知道能否支持一二级目录可以“open in window”，或者直接跳过一二级目录。）

**Comment by axetroy** [comment]
@FantasyGao 
能描述清除一点吗，不太明白。

> 当我打开已有的git项目时, 依旧按照第一级‘域名类’，第二级‘用户类’，第三级‘项目类’，前两级不可以‘‘open in window’’，但实际上此时的项目没有一二级分类。

自行 clone 的项目，目录结果没有分层，怎么分类

**Comment by FantasyGao** [comment]
@axetroy 
是的，没有分类。因为我想把我的几个项目就放到gpm下，不用分类，或者就分一层，然后直接右键“open in window”。现在不支持呢，是否可以配置，谢谢。

**Comment by axetroy** [comment]
@FantasyGao 

以前我在写命令行工具的时候，确实写了这么一个导入功能 ``gpm import xxx项目``， 但是后来就废除了。

为什么需要导入呢，从头导入新项目，废除旧目录，没什么不好的。

gpm做的就是目录分层

**源** > **用户** > **项目**

分了3个层级，方便管理目录。即便你使用文件浏览器打开目录，都能比较清晰的找到项目。

如你所说，分1层，不是不可以，而是违背了初衷，所以，应该是不会实现的

**Comment by FantasyGao** [comment]
@axetroy 主要是工作的多个项目都是一个源的一个用户下的，每次都要点两层进去打开工程，不是很方便。全放到上面的workplace又嫌打开多个工程乱。。。

**Comment by axetroy** [comment]
@FantasyGao 
我懂你的意思.

但是所以的项目都放在一级目录中，离开了扩展，想要找到项目就显得非常困难. 具有依赖性。

关于要点进2层才能打开工程目录，后续会有优化。

增加一个star功能，快速打开项目

**Comment by FantasyGao** [comment]
@axetroy 
嗯，是的，我建议就是源和用户都可以选择‘‘open in window’’,打开之后就是多个工程，自然也就解决这个问题。
感谢开源出来，已star，关注更新ing...

**Comment by axetroy** [comment]
请问还有其他的建议吗
