### ISSUE TITLE
Feature: Show flat project names in project manager

### ISSUE THREAD

**Issue by Zyrsha** [axetroy/vscode-gpm#20]
Hi,

I am using your extension a lot. I have a couple hundred git repositories in my GPM.

It's difficult to work with a big list of repositories because we can only see the usernames at the top level.

I wish I could see the actual repo names instead of only the usernames. Sometimes I stupidly click to expand a bunch of repos because I forgot who the author was.

**Feature request for option:**
[x] Show flat project names in project manager

Instead of showing:
```
gpmer
+- gpm.js
```

It would show:
```
gpmer/gpm.js
```

**Comment by axetroy** [comment]
Thanks for your feedback.
this's a breaking change.

This extension inspired by Golang module design, I don't think it's worth to make flat.

If you don't remember the project name.

You can use **gpm search** command in `vs code`

This is the implementation of fuzzy search, you only need keywords to search

![2018-12-18 20 11 10](https://user-images.githubusercontent.com/9758711/50153324-172a2780-0301-11e9-8031-a3c7776a0259.png)

**Comment by Zyrsha** [comment]
How is it a breaking change to provide an option for this?

The GPM is almost unusable for because I cannot see the names of the repositories any more. It's just a huge list of usernames. *Very difficult* to work with.

I am requesting this because I cannot use the extension any longer because this is a serious problem causing lost time, frustration. I would use this extension 10x more frequently if I could actually *see the list of repos*

 If it is not resolved then unfortunately I have to fork the extension. I am asking you please, so that I do not have to fork it.

**Comment by axetroy** [comment]
@Zyrsha

yeah. It should be ok to provide an option for this.

option to show the flat project name. nothing be breaking

It need another tree implementation.

I am busy with others. it may be days

**Comment by Zyrsha** [comment]
Thanks so much for your understanding. No worries on time, I am grateful

**Comment by axetroy** [comment]
update in version@1.1.0.

checkout the configuration
