### ISSUE TITLE
$HOME/gpm 在windows下不起作用

### ISSUE THREAD

**Issue by liaoyinglong** [axetroy/vscode-gpm#7]
环境：
- win 10 
- vsocode 最新版
- vscode-gpm最新版
- 写死路径可行

![gpm](https://user-images.githubusercontent.com/23382699/38225184-4515c49e-3726-11e8-842d-43c6d57e4380.png)
![gmp2](https://user-images.githubusercontent.com/23382699/38225185-461df654-3726-11e8-9dd0-6ee009fff8f1.png)
![gmp3](https://user-images.githubusercontent.com/23382699/38225186-470b1268-3726-11e8-8226-40c8994ef4ff.png)

**Comment by axetroy** [comment]
感谢反馈，确实写死路径是可以的。

Windows下呢我没有测试机进行测试，下一版本尝试摸黑修复它

**Comment by axetroy** [comment]
已在新版本尝试修复了，``$HOME/gpm``应该能够被正确解析了

劳烦能否给个反馈

**Comment by liaoyinglong** [comment]
已经好了！！

thank you
